export const terminalCommands: Record<string, string[]> = {
  help: [
    'Available commands:',
    '  whoami          - Display user information',
    '  skills          - Show technical skills',
    '  projects        - List recent projects',
    '  contact         - Get contact information',
    '  experience      - View work history',
    '  education       - Academic background',
    '  neofetch        - System information',
    '  matrix          - Enter the matrix',
    '  sudo make me a sandwich - XKCD reference',
    '  clear           - Clear terminal',
    '',
    'Try typing any command to explore!'
  ],
  
  whoami: [
    'USER: John Developer',
    'ROLE: Senior Full-Stack Engineer',
    'STATUS: Available for opportunities',
    'CLEARANCE: Level 9 Code Wizard',
    '',
    'A passionate developer who lives at the intersection of',
    'creativity and technology. I build digital experiences',
    'that push boundaries and solve real problems.',
    '',
    'When not coding, you can find me exploring the latest',
    'in AI, contributing to open source, or teaching others',
    'the art of clean code.'
  ],
  
  skills: [
    'TECHNICAL PROFICIENCIES:',
    '========================',
    '',
    'Languages:',
    '  JavaScript/TypeScript  ████████████ 95%',
    '  Python                ███████████  90%',
    '  Go                    ████████     80%',
    '  Rust                  ██████       60%',
    '  SQL                   ████████████ 95%',
    '',
    'Frontend:',
    '  React/Next.js         ████████████ 95%',
    '  Vue.js                ████████     80%',
    '  CSS/Tailwind          ████████████ 95%',
    '  WebGL/Three.js        ███████      70%',
    '',
    'Backend:',
    '  Node.js               ████████████ 95%',
    '  Django/FastAPI        ████████████ 95%',
    '  GraphQL               █████████    85%',
    '  Microservices         ████████████ 95%',
    '',
    'Cloud & DevOps:',
    '  AWS/GCP               ████████████ 95%',
    '  Docker/K8s            █████████    85%',
    '  CI/CD                 ████████████ 95%',
    '  Terraform             ███████      70%'
  ],
  
  projects: [
    'RECENT_PROJECTS.LOG:',
    '===================',
    '',
    '[2024] Neural Network Visualizer',
    '  → Interactive ML visualization platform',
    '  → Tech: React, D3.js, TensorFlow.js',
    '  → Status: Production',
    '',
    '[2024] Blockchain Explorer',
    '  → Decentralized transaction analyzer',
    '  → Tech: Web3.js, Solidity, React',
    '  → Status: Beta',
    '',
    '[2023] AI Conversation Engine',
    '  → Advanced chatbot with NLP',
    '  → Tech: Python, OpenAI, FastAPI',
    '  → Status: Production',
    '',
    '[2023] Quantum Circuit Simulator',
    '  → Browser-based quantum computing',
    '  → Tech: WebAssembly, TypeScript',
    '  → Status: Research Phase',
    '',
    'Use mouse hover on project tiles above for visual preview!'
  ],
  
  contact: [
    'ESTABLISHING CONNECTION...',
    '========================',
    '',
    'Email:    john.developer@example.com',
    'Phone:    +1 (555) 123-4567',
    'LinkedIn: /in/johndeveloper',
    'GitHub:   /johndeveloper',
    'Website:  johndeveloper.dev',
    '',
    'Location: San Francisco, CA',
    'Timezone: PST (UTC-8)',
    '',
    'Response Time: Usually within 24 hours',
    'Availability: Open to full-time opportunities',
    '',
    'PGP Key: Available upon request',
    'Encrypted communications welcome'
  ],
  
  experience: [
    'WORK_HISTORY.LOG:',
    '================',
    '',
    '[2020-2024] Senior Full-Stack Engineer @ TechCorp',
    '  • Led development team of 8 engineers',
    '  • Architected scalable microservices handling 1M+ requests/day',
    '  • Improved system performance by 40% through optimization',
    '  • Mentored junior developers and established coding standards',
    '',
    '[2018-2020] Software Engineer @ StartupX',
    '  • Built MVP from scratch using React and Node.js',
    '  • Implemented real-time features with WebSocket integration',
    '  • Collaborated with designers on pixel-perfect implementations',
    '  • Scaled application from 0 to 100K users',
    '',
    '[2016-2018] Junior Developer @ DevAgency',
    '  • Developed client websites and web applications',
    '  • Worked with diverse tech stacks and frameworks',
    '  • Gained experience in agile development practices',
    '  • Contributed to open-source projects'
  ],
  
  education: [
    'ACADEMIC_RECORDS.DB:',
    '===================',
    '',
    '[2016-2018] Master of Science, Computer Science',
    '  Institution: Massachusetts Institute of Technology',
    '  GPA: 3.9/4.0',
    '  Focus: Machine Learning & Distributed Systems',
    '  Thesis: "Optimizing Neural Networks for Edge Computing"',
    '',
    '[2012-2016] Bachelor of Science, Software Engineering',
    '  Institution: Stanford University',
    '  GPA: 3.8/4.0',
    '  Magna Cum Laude',
    '  Activities: ACM Programming Team, CS Teaching Assistant',
    '',
    'CERTIFICATIONS:',
    '  • AWS Solutions Architect Professional',
    '  • Google Cloud Professional Developer',
    '  • Kubernetes Administrator (CKA)',
    '  • Certified Ethical Hacker (CEH)'
  ],
  
  neofetch: [
    '                   -`                    john@portfolio',
    '                  .o+`                   ---------------',
    '                 `ooo/                   OS: ArchLinux Developer Edition',
    '                `+oooo:                  Host: Creative Workstation Pro',
    '               `+oooooo:                 Kernel: 6.1.0-productivity',
    '               -+oooooo+:                Uptime: 2 years, 47 days',
    '             `/:-:++oooo+:               Packages: 1337 (npm), 420 (pip)',
    '            `/++++/+++++++:              Shell: zsh 5.9',
    '           `/++++++++++++++:             Resolution: 3840x2160',
    '          `/+++ooooooooooooo/`           DE: Custom (React-based)',
    '         ./ooosssso++osssssso+`          WM: i3-gaps',
    '        .oossssso-````/ossssss+`         Theme: Glitchcore Dark',
    '       -osssssso.      :ssssssso.        Icons: Lucide React',
    '      :osssssss/        osssso+++.       Terminal: Alacritty',
    '     /ossssssss/        +ssssooo/-       CPU: Intel i9-13900K (24) @ 5.8GHz',
    '   `/ossssso+/:-        -:/+osssso+-     GPU: NVIDIA RTX 4090',
    '  `+sso+:-`                 `.-/+oso:    Memory: 64GB DDR5-5600',
    ' `++:.                           `-/+/   Disk: 4TB NVMe SSD',
    ' .`                                 `/   Coding: 16+ hours/day'
  ],
  
  matrix: [
    'Entering the matrix...',
    '',
    '01001000 01100101 01101100 01101100 01101111',
    '01010111 01101111 01110010 01101100 01100100',
    '',
    'REALITY.EXE has stopped working',
    'Loading alternative dimension...',
    '',
    'Welcome to the digital realm where code becomes reality',
    'and reality becomes code. You are now part of the system.',
    '',
    'There is no spoon. There is only JavaScript.',
    '',
    'Connection established to Node 127.0.0.1:3000',
    'You have been granted admin privileges.',
    'Use your powers wisely, Neo.'
  ],
  
  'sudo make me a sandwich': [
    'Okay, making you a sandwich...',
    '',
    '🥪 [████████████████████████████████] 100%',
    '',
    'Sandwich construction complete!',
    '',
    'Ingredients:',
    '  • 2 slices of artisanal sourdough bread',
    '  • Premium turkey and swiss cheese',
    '  • Fresh lettuce, tomatoes, and pickles',
    '  • Secret sauce (proprietary algorithm)',
    '  • A sprinkle of love and XKCD humor',
    '',
    'Your sandwich has been delivered virtually.',
    'Physical manifestation requires additional hardware.',
    '',
    'Error 418: I\'m a teapot, not a sandwich maker.',
    'But I appreciate the sudo privileges! 😄'
  ],
  
  clear: [''],
  
  ls: [
    'portfolio.exe     resume.corrupt    projects/',
    'achievements/     terminal.log      matrix.neo',
    'skills.json       contact.vcf       secrets/'
  ],
  
  pwd: ['/home/portfolio/digital_realm'],
  
  date: [new Date().toString()],
  
  uptime: ['System uptime: 2 years, 47 days, 13 hours, 37 minutes'],
  
  history: [
    '1  whoami',
    '2  skills',
    '3  ls -la',
    '4  cat secrets/easter_eggs.txt',
    '5  sudo rm -rf /*  # just kidding!',
    '6  git commit -m "life update"',
    '7  npm run life',
    '8  history'
  ]
};